# Generated by Django 4.2.7 on 2023-12-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
