# Generated by Django 4.2.7 on 2024-02-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='registrar_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
